# Generated by Django 2.2.16 on 2022-01-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220124_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='6WkAm4JUDjVFVxZ', editable=False, help_text='UUID код подтверждения для получения токена', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
