# Generated by Django 2.2.16 on 2022-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220124_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='Xb0RiZ6OSZdJPVt', editable=False, help_text='UUID код подтверждения для получения токена', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
