# Generated by Django 2.2.16 on 2022-01-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220125_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='pK4C2OePgxjkQlk', editable=False, help_text='UUID код подтверждения для получения токена', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
