# Generated by Django 2.2.16 on 2022-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220126_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='8jVmWEqzEOMHkvD', editable=False, help_text='UUID код подтверждения для получения токена', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
